In [1]:
import pandas as pd 
import numpy as np 
from sklearn import linear_model
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score

In [2]:
hp = './datas/price_availability.csv'
hl = './datas/listings_final.csv'
prices = pd.read_csv(hp, sep=';')
listing = pd.read_csv(hl, sep=';')

In [3]:
prices = prices.groupby(['listing_id']).mean()
prices

available  local_price  min_nights
listing_id                                    
5396         0.011494   102.363985    2.000000
7397         0.168297   110.107632   11.000000
9342         0.309198   396.863014    2.784736
10010        0.254593   136.154856    4.955381
10270        0.511688   105.779221    4.937662
...               ...          ...         ...
28836096     0.082707   321.428571    1.022556
28838519     0.083333    54.483333    5.000000
28840013     0.743083   112.122530    2.000000
28846494     0.225564   168.037594    4.000000
28851976     0.812030   128.000000    2.000000

[11749 rows x 3 columns]

In [4]:
listing = listing.groupby('listing_id').mean()
listing

Unnamed: 0   latitude  longitude  person_capacity  beds  bedrooms  \
listing_id                                                                      
56093               12  48.867284   2.358431                4     2         1   
57207               13  48.846184   2.304455                2     1         1   
114543              19  48.849530   2.290219                2     1         1   
149534               9  48.866360   2.361844                4     2         1   
164255              28  48.861398   2.364299                4     2         1   
...                ...        ...        ...              ...   ...       ...   
28684174           662  48.879223   2.292382                5     0         1   
28709644           745  48.872202   2.298349                4     2         1   
28751412            88  48.880923   2.314568                2     1         0   
28774896           159  48.852915   2.314519                2     1         1   
28792796           998  48.870109   2.321475                6     4         2   

            bathrooms  is_rebookable  is_new_listing  is_fully_refundable  \
listing_id                                                                  
56093             1.0          False           False                 True   
57207             1.0          False           False                 True   
114543            1.0          False           False                 True   
149534            1.0          False           False                 True   
164255            1.0          False           False                 True   
...               ...            ...             ...                  ...   
28684174          1.0          False            True                 True   
28709644          1.0          False            True                 True   
28751412          1.0          False            True                 True   
28774896          1.0          False            True                 True   
28792796          1.5          False            True                 True   

            is_host_highly_rated  is_business_travel_ready  \
listing_id                                                   
56093                       True                     False   
57207                      False                     False   
114543                      True                     False   
149534                      True                     False   
164255                     False                     False   
...                          ...                       ...   
28684174                   False                     False   
28709644                   False                     False   
28751412                   False                     False   
28774896                   False                     False   
28792796                   False                     False   

            pricing_weekly_factor  pricing_monthly_factor  
listing_id                                                 
56093                        0.88                     1.0  
57207                        0.87                     1.0  
114543                       0.90                     0.9  
149534                       1.00                     0.4  
164255                       1.00                     1.0  
...                           ...                     ...  
28684174                     1.00                     1.0  
28709644                     1.00                     1.0  
28751412                     1.00                     1.0  
28774896                     1.00                     1.0  
28792796                     1.00                     1.0  

[1000 rows x 14 columns]

In [5]:
full = pd.merge(prices[['local_price']], listing, on=['listing_id'])
full

local_price  Unnamed: 0   latitude  longitude  person_capacity  \
listing_id                                                                   
56093        170.000000          12  48.867284   2.358431                4   
57207         49.952756          13  48.846184   2.304455                2   
114543       107.374026          19  48.849530   2.290219                2   
149534       169.000000           9  48.866360   2.361844                4   
164255        75.876209          28  48.861398   2.364299                4   
...                 ...         ...        ...        ...              ...   
28684174     725.175781         662  48.879223   2.292382                5   
28709644     475.000000         745  48.872202   2.298349                4   
28751412     117.000000          88  48.880923   2.314568                2   
28774896     156.397468         159  48.852915   2.314519                2   
28792796      49.184211         998  48.870109   2.321475                6   

            beds  bedrooms  bathrooms  is_rebookable  is_new_listing  \
listing_id                                                             
56093          2         1        1.0          False           False   
57207          1         1        1.0          False           False   
114543         1         1        1.0          False           False   
149534         2         1        1.0          False           False   
164255         2         1        1.0          False           False   
...          ...       ...        ...            ...             ...   
28684174       0         1        1.0          False            True   
28709644       2         1        1.0          False            True   
28751412       1         0        1.0          False            True   
28774896       1         1        1.0          False            True   
28792796       4         2        1.5          False            True   

            is_fully_refundable  is_host_highly_rated  \
listing_id                                              
56093                      True                  True   
57207                      True                 False   
114543                     True                  True   
149534                     True                  True   
164255                     True                 False   
...                         ...                   ...   
28684174                   True                 False   
28709644                   True                 False   
28751412                   True                 False   
28774896                   True                 False   
28792796                   True                 False   

            is_business_travel_ready  pricing_weekly_factor  \
listing_id                                                    
56093                          False                   0.88   
57207                          False                   0.87   
114543                         False                   0.90   
149534                         False                   1.00   
164255                         False                   1.00   
...                              ...                    ...   
28684174                       False                   1.00   
28709644                       False                   1.00   
28751412                       False                   1.00   
28774896                       False                   1.00   
28792796                       False                   1.00   

            pricing_monthly_factor  
listing_id                          
56093                          1.0  
57207                          1.0  
114543                         0.9  
149534                         0.4  
164255                         1.0  
...                            ...  
28684174                       1.0  
28709644                       1.0  
28751412                       1.0  
28774896                       1.0  
28792796                       1.0  

[999 rows x 15 c

In [20]:
# y prices
# x listing => person_capactity, bedrooms
y = np.array(full[['local_price']])
x = np.array(full[['person_capacity', 'bedrooms', 'bathrooms']])
x

array([[4. , 1. , 1. ],
       [2. , 1. , 1. ],
       [2. , 1. , 1. ],
       ...,
       [2. , 0. , 1. ],
       [2. , 1. , 1. ],
       [6. , 2. , 1.5]])

In [21]:
y

array([[ 170.        ],
       [  49.95275591],
       [ 107.37402597],
       [ 169.        ],
       [  75.8762089 ],
       [ 284.35356201],
       [  36.58961039],
       [ 300.        ],
       [ 101.37984496],
       [  67.20833333],
       [  60.74093264],
       [  38.        ],
       [  92.        ],
       [  66.21204188],
       [  79.68041237],
       [  90.09819121],
       [ 170.        ],
       [ 115.7544757 ],
       [ 283.76115486],
       [ 144.74424552],
       [ 347.67015707],
       [ 115.        ],
       [ 105.        ],
       [ 154.65384615],
       [ 380.        ],
       [  44.16569201],
       [ 233.69170984],
       [ 146.        ],
       [ 147.96623377],
       [ 105.        ],
       [ 163.47286822],
       [ 190.        ],
       [ 180.95287958],
       [ 128.8630491 ],
       [  44.47368421],
       [ 163.28571429],
       [  94.        ],
       [  94.97619048],
       [ 218.96373057],
       [ 234.89460154],
       [ 300.78640777],
       [  62.   

In [38]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.30, random_state=42)
y_test

array([[  43.14368932],
       [1300.        ],
       [  57.88653846],
       [ 297.76315789],
       [  55.34933333],
       [ 600.        ],
       [  28.4947644 ],
       [  17.9766537 ],
       [  79.81038961],
       [ 250.19379845],
       [ 221.99738903],
       [ 114.95833333],
       [ 350.        ],
       [ 170.        ],
       [ 195.        ],
       [ 166.328125  ],
       [ 340.81007752],
       [  93.18393782],
       [ 160.02645503],
       [ 203.41755319],
       [ 146.57519789],
       [ 149.        ],
       [ 329.36832061],
       [ 182.30769231],
       [ 299.        ],
       [ 240.        ],
       [ 108.        ],
       [ 118.78473581],
       [ 250.        ],
       [  47.59585492],
       [ 126.32198953],
       [ 184.30628272],
       [  93.35248042],
       [ 176.37075718],
       [  59.        ],
       [ 148.76804124],
       [  30.        ],
       [ 425.        ],
       [ 226.89210526],
       [  71.01804124],
       [ 204.6342711 ],
       [  79.   

In [23]:
y_train.shape

(699, 1)

In [24]:
y_test.shape

(300, 1)

In [25]:
x_train.shape

(699, 3)

In [26]:
x_test.shape

(300, 3)

In [27]:
reg = linear_model.LinearRegression().fit(x_train, y_train)
reg

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [28]:
print("Coefficients beta_j :\n{}\nCoefficients INTERCEPT beta0 :\n{}".format(reg.coef_,reg.intercept_))

Coefficients beta_j :
[[29.22157692 14.61898054 86.34152526]]
Coefficients INTERCEPT beta0 :
[-46.48417235]


In [33]:
y_pred = reg.predict(x_test)
y_pred

array([[126.868673  ],
       [534.01051785],
       [112.91948729],
       [215.20319858],
       [ 98.30050675],
       [345.3852813 ],
       [112.91948729],
       [ 83.69791037],
       [112.91948729],
       [518.73812664],
       [185.98162166],
       [ 98.30050675],
       [316.16370438],
       [171.36264112],
       [156.09024991],
       [244.4247755 ],
       [185.98162166],
       [171.36264112],
       [316.16370438],
       [214.53340375],
       [112.91948729],
       [112.91948729],
       [433.70342272],
       [112.91948729],
       [112.91948729],
       [330.76630076],
       [171.36264112],
       [ 98.30050675],
       [156.74366058],
       [112.91948729],
       [ 98.30050675],
       [142.1410642 ],
       [156.74366058],
       [259.04375604],
       [ 98.30050675],
       [171.36264112],
       [112.91948729],
       [272.32314692],
       [330.76630076],
       [ 98.30050675],
       [112.91948729],
       [112.91948729],
       [214.53340375],
       [388

In [35]:
mean_squared_error(y_test, y_pred)

21600.006742647594

In [36]:
r2_score(y_test, y_pred)

0.3772870887592449